from test_support import *
import string

exec_cmd('ada2wsdl',
         ['-q', '-d', '-f', '-Pcallsh', 'callsh.ads',
          '-o', 'callsh.wsdl'])

with open('callsh.wsdl') as result:
    for l in result.readlines():
        if string.find(l, "Generated by") == -1:
            print l
