<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="GetCasService"
                  targetNamespace="http://simple.doc.net/sd"
                  xmlns="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
  <types>
    <schema>
      <xsd:simpleType name="ExampleType">
        <xsd:restriction base="xs:string">
          <xsd:enumeration value="A-Example"/>
          <xsd:enumeration value="B-EXAMPLE"/>
          <xsd:enumeration value="C-example"/>
          <xsd:enumeration value="NEW"/>
        </xsd:restriction>
      </xsd:simpleType>
    </schema>
  </types>

  <message name="myMethodRequest">
    <part name="ex" element="ExampleType"/>
  </message>

  <message name="empty"/>

  <portType name="PT">
    <operation name="call">
      <input message="myMethodRequest"/>
      <output message="empty"/>
    </operation>
  </portType>

<binding name="EnumValBinding" type="EnumVal">
  <soap:binding style="document"
                transport="http://schemas.xmlsoap.org/soap/http" />

  <operation name="call">
    <soap:operation soapAction="http://me.here.net/call" />
    <wsdl:input>
      <soap:body use="literal" />
    </wsdl:input>
    <wsdl:output>
      <soap:body use="literal" />
    </wsdl:output>
  </operation>
</binding>

<wsdl:service name="EnumValService">
  <port name="EnumValPort" binding="EnumValBinding">
    <soap:address location="http://localhost:1234" />
  </port>
</wsdl:service>

</wsdl:definitions>
