
/* 
   $Id

   This program is used to get some OS specific settings
*/

#include <stdio.h>

#ifndef _WIN32
#include <sys/poll.h>
#endif

int
main (void)
{
  const int s_long   = sizeof (long);
  const int s_int    = sizeof (int);
  const int s_short  = sizeof (short);

#ifdef _WIN32
  const int s_nfds_t      = s_long;
  const int s_fd_type     = s_int;
  const int s_events_type = s_short;
  const int v_POLLIN      = 1;
  const int v_POLLPRI     = 2;
  const int v_POLLOUT     = 4;
  const int v_POLLERR     = 8;
  const int v_POLLHUP     = 16;
  const int v_POLLNVAL    = 32;
#else
  const struct pollfd v_pollfd;
  const int s_nfds_t      = sizeof (nfds_t);
  const int s_fd_type     = sizeof (v_pollfd.fd);
  const int s_events_type = sizeof (v_pollfd.events);
  const int v_POLLIN      = POLLIN;
  const int v_POLLPRI     = POLLPRI;
  const int v_POLLOUT     = POLLOUT;
  const int v_POLLERR     = POLLERR;
  const int v_POLLHUP     = POLLHUP;
  const int v_POLLNVAL    = POLLNVAL;
#endif

  printf ("\n--  AUTOMATICALLY GENERATED, DO NOT EDIT THIS FILE\n\n");
  printf ("with Interfaces.C;\n\n");
  printf ("package AWS.OS_Lib.Definitions is\n\n");
  printf ("   use Interfaces;\n\n");

  /* POLL constants */

  printf ("   POLLIN   : constant := %d;\n", v_POLLIN);
  printf ("   POLLPRI  : constant := %d;\n", v_POLLPRI);
  printf ("   POLLOUT  : constant := %d;\n", v_POLLOUT);
  printf ("   POLLERR  : constant := %d;\n", v_POLLERR);
  printf ("   POLLHUP  : constant := %d;\n", v_POLLHUP);
  printf ("   POLLNVAL : constant := %d;\n\n", v_POLLNVAL);
  
  /* nfds_t */

  if (s_nfds_t == s_long)
    printf ("   type nfds_t is new C.unsigned_long;\n\n");
  else
    printf ("   type nfds_t is new C.unsigned;\n\n");

  /* FD_Type */

  if (s_fd_type == s_long) {
    printf ("   type FD_Type is mod 2 ** C.unsigned_long'Size;\n");
    printf ("   for FD_Type'Size use C.unsigned_long'Size;\n\n");
  } else {
    printf ("   type FD_Type is mod 2 ** C.int'Size;\n");
    printf ("   for FD_Type'Size use C.int'Size;\n\n");
  }

  /* Events_Type */

  if (s_events_type == s_long) {
    printf ("   type Events_Type is mod 2 ** C.unsigned_long'Size;\n");
    printf ("   for Events_Type'Size use C.unsigned_long'Size;\n\n");
  } else if (s_events_type == s_int) {
    printf ("   type Events_Type is mod 2 ** C.int'Size;\n");
    printf ("   for Events_Type'Size use C.int'Size;\n\n");
  } else {
    printf ("   type Events_Type is mod 2 ** C.short'Size;\n");
    printf ("   for Events_Type'Size use C.short'Size;\n\n");
  }

  printf ("end AWS.OS_Lib.Definitions;\n");

  return 0;
}
