#!/bin/sh
if [ $# = 0 ]; then
  echo "Usage: $0 <file to translate>"
  exit 0
fi

SOURCE=$1
TARGET=${SOURCE}.texi

gawk 'BEGIN{out=1}$1=="end"&&substr($0,1,1)=="e"{out=1}out==1{print}$1=="private"&&out==1{out=0; print "   --  implementation removed"}' ${SOURCE} > genout

echo "@smallexample"      >${TARGET}
if [ $# = 1 ]; then
echo "@cartouche"        >>${TARGET}
echo "@group"            >>${TARGET}
fi
echo ""                  >>${TARGET}
sed -f ada.sed genout    >>${TARGET}
echo ""                  >>${TARGET}
if [ $# = 1 ]; then
echo "@end group"        >>${TARGET}
echo "@end cartouche"    >>${TARGET}
fi
echo "@end smallexample" >>${TARGET}
