<?xml version="1.0" encoding="UTF-8"?>
<definitions name="WSDL_4"
             targetNamespace="urn:aws:WSDL_4"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:tns="urn:aws:WSDL_4">

   <types>
      <schema xmlns="http://www.w3.org/2000/10/XMLSchema">

         <simpleType name="Character">
            <restriction base="xsd:string">
	       <length value="10"/>
            </restriction>
         </simpleType>

      </schema>
   </types>

   <message name="Try_Request">
      <part name="Param1" type="Character"/>
   </message>

   <portType name="WSDL_4_PortType">

      <operation name="Try">
         <input message="Try_Request"/>
      </operation>

   </portType>

   <binding name="WSDL_4_Binding" type="WSDL_4_PortType">
      <soap:binding style="rpc"
         transport="http://schemas.xmlsoap.org/soap/http"/>

      <operation name="Try">
         <soap:operation soapAction="Try"/>
         <input>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:aws:WSDL_4"
               use="encoded"/>
         </input>
         <output>
            <soap:body
               encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
               namespace="urn:aws:WSDL_4"
               use="encoded"/>
         </output>
      </operation>

   </binding>

   <service name="WSDL_PARSE_1">
      <port name="WSDL_4_Port" binding="WSDL_4_Binding">
         <soap:address location="http://localhost:7704"/>
      </port>
   </service>
</definitions>
